In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv("/content/Students Performance.csv")

In [44]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [45]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [46]:
encoded_data = pd.get_dummies(df[['gender', 'race/ethnicity', 'lunch', 'test preparation course']], drop_first=True)

In [47]:
from sklearn.preprocessing import OrdinalEncoder

# Correct the categories to match the actual values in the dataframe
# and include all unique values
education_order = [['some high school', 'high school', 'some college', "associate's degree", "bachelor's degree", "master's degree"]]
encoder = OrdinalEncoder(categories=education_order)
df['education_level_encoded'] = encoder.fit_transform(df[['parental level of education']])

In [48]:
df = df.drop(['gender', 'race/ethnicity', 'lunch', 'test preparation course','education_level_encoded'], axis=1)

In [49]:
df

    parental level of education  math score  reading score  writing score
0             bachelor's degree          72             72             74
1                  some college          69             90             88
2               master's degree          90             95             93
3            associate's degree          47             57             44
4                  some college          76             78             75
..                          ...         ...            ...            ...
995             master's degree          88             99             95
996                 high school          62             55             55
997                 high school          59             71             65
998                some college          68             78             77
999                some college          77             86             86

[1000 rows x 4 columns]

In [50]:
data = pd.concat([df, encoded_data], axis=1)

In [51]:
data

,parental level of education,math score,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none
0,bachelor's degree,72,72,74,False,True,False,False,False,True,True
1,some college,69,90,88,False,False,True,False,False,True,False
2,master's degree,90,95,93,False,True,False,False,False,True,True
3,associate's degree,47,57,44,True,False,False,False,False,False,True
4,some college,76,78,75,True,False,True,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...
995,master's degree,88,99,95,False,False,False,False,True,True,False
996,high school,62,55,55,True,False,True,False,False,False,True
997,high school,59,71,65,False,False,True,False,False,False,False
998,some college,68,78,77,False,False,False,True,False,True,False
999,some college,77,86,86,False,False,False,True,False,False,True

In [52]:
data = data.applymap(lambda x: int(x) if isinstance(x, bool) else x)

<ipython-input-52-de3c5dfd8026>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  data = data.applymap(lambda x: int(x) if isinstance(x, bool) else x)

In [53]:
data

,parental level of education,math score,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none
0,bachelor's degree,72,72,74,0,1,0,0,0,1,1
1,some college,69,90,88,0,0,1,0,0,1,0
2,master's degree,90,95,93,0,1,0,0,0,1,1
3,associate's degree,47,57,44,1,0,0,0,0,0,1
4,some college,76,78,75,1,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
995,master's degree,88,99,95,0,0,0,0,1,1,0
996,high school,62,55,55,1,0,1,0,0,0,1
997,high school,59,71,65,0,0,1,0,0,0,0
998,some college,68,78,77,0,0,0,1,0,1,0
999,some college,77,86,86,0,0,0,1,0,0,1

In [54]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Select the numerical columns for standardization
numerical_columns = ['math score','reading score','writing score'	]  # Replace with your columns
data[numerical_columns] = scaler.fit_transform(data[numerical_columns])

In [55]:
numerical_columns

['math score', 'reading score', 'writing score']

In [56]:
data

,parental level of education,math score,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none
0,bachelor's degree,0.390024,0.193999,0.391492,0,1,0,0,0,1,1
1,some college,0.192076,1.427476,1.313269,0,0,1,0,0,1,0
2,master's degree,1.577711,1.770109,1.642475,0,1,0,0,0,1,1
3,associate's degree,-1.259543,-0.833899,-1.583744,1,0,0,0,0,0,1
4,some college,0.653954,0.605158,0.457333,1,0,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
995,master's degree,1.445746,2.044215,1.774157,0,0,0,0,1,1,0
996,high school,-0.269803,-0.970952,-0.859491,1,0,1,0,0,0,1
997,high school,-0.467751,0.125472,-0.201079,0,0,1,0,0,0,0
998,some college,0.126093,0.605158,0.589015,0,0,0,1,0,1,0
999,some college,0.719937,1.153370,1.181586,0,0,0,1,0,0,1

In [57]:
np.round(data.describe(), 1)

,math score,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none
count,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0
mean,0.0,0.0,-0.0,0.5,0.2,0.3,0.3,0.1,0.6,0.6
std,1.0,1.0,1.0,0.5,0.4,0.5,0.4,0.3,0.5,0.5
min,-4.4,-3.6,-3.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,-0.6,-0.7,-0.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,-0.0,0.1,0.1,0.0,0.0,0.0,0.0,0.0,1.0,1.0
75%,0.7,0.7,0.7,1.0,0.0,1.0,1.0,0.0,1.0,1.0
max,2.2,2.1,2.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [58]:
np.round(df.describe(),1)

       math score  reading score  writing score
count      1000.0         1000.0         1000.0
mean         66.1           69.2           68.1
std          15.2           14.6           15.2
min           0.0           17.0           10.0
25%          57.0           59.0           57.8
50%          66.0           70.0           69.0
75%          77.0           79.0           79.0
max         100.0          100.0          100.0

In [73]:
# Assuming data['math_score'] is already standardized
data['score_category'] = pd.cut(data['math score'], bins=[-3, -1, 1, 3], labels=['Low', 'Medium', 'High'])

In [74]:
data

,parental level of education,math score,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none,score_category
0,bachelor's degree,0.390024,0.193999,0.391492,0,1,0,0,0,1,1,Medium
1,some college,0.192076,1.427476,1.313269,0,0,1,0,0,1,0,Medium
2,master's degree,1.577711,1.770109,1.642475,0,1,0,0,0,1,1,High
3,associate's degree,-1.259543,-0.833899,-1.583744,1,0,0,0,0,0,1,Low
4,some college,0.653954,0.605158,0.457333,1,0,1,0,0,1,1,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...
995,master's degree,1.445746,2.044215,1.774157,0,0,0,0,1,1,0,High
996,high school,-0.269803,-0.970952,-0.859491,1,0,1,0,0,0,1,Medium
997,high school,-0.467751,0.125472,-0.201079,0,0,1,0,0,0,0,Medium
998,some college,0.126093,0.605158,0.589015,0,0,0,1,0,1,0,Medium
999,some college,0.719937,1.153370,1.181586,0,0,0,1,0,0,1,Medium

In [67]:
# Fill NaN values with a default value (e.g., mean or median)
data['math score'].fillna(data['math score'].mean(), inplace=True)

# Now apply pd.cut()
data['score_category'] = pd.cut(data['math score'], bins=[0, 50, 75, 100], labels=['Low', 'Medium', 'High'])

<ipython-input-67-27d0da2509ec>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['math score'].fillna(data['math score'].mean(), inplace=True)

In [75]:
data['score_category']

0      Medium
1      Medium
2        High
3         Low
4      Medium
        ...
995      High
996    Medium
997    Medium
998    Medium
999    Medium
Name: score_category, Length: 1000, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [76]:
data['score_category']

0      Medium
1      Medium
2        High
3         Low
4      Medium
        ...
995      High
996    Medium
997    Medium
998    Medium
999    Medium
Name: score_category, Length: 1000, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [77]:
# Check minimum and maximum values
print(data['math score'].min(), data['math score'].max())

-4.360728089898279 2.2375380207983255

In [79]:
#  Drop the original math_score column
data.drop(columns=['math score'], inplace=True)

In [80]:
data.head()

,parental level of education,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none,score_category
0,bachelor's degree,0.193999,0.391492,0,1,0,0,0,1,1,Medium
1,some college,1.427476,1.313269,0,0,1,0,0,1,0,Medium
2,master's degree,1.770109,1.642475,0,1,0,0,0,1,1,High
3,associate's degree,-0.833899,-1.583744,1,0,0,0,0,0,1,Low
4,some college,0.605158,0.457333,1,0,1,0,0,1,1,Medium

In [83]:
# Assuming data['math_score'] is already standardized
data['read_category'] = pd.cut(data['reading score'], bins=[-3, -1, 1, 3], labels=['Low', 'Medium', 'High'])

In [84]:
data['read_category']

0      Medium
1        High
2        High
3      Medium
4      Medium
        ...
995      High
996    Medium
997    Medium
998    Medium
999      High
Name: read_category, Length: 1000, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [85]:
# Assuming data['math_score'] is already standardized
data['writing_score'] = pd.cut(data['writing score'], bins=[-3, -1, 1, 3], labels=['Low', 'Medium', 'High'])

In [86]:
data['writing_score']

0      Medium
1        High
2        High
3         Low
4      Medium
        ...
995      High
996    Medium
997    Medium
998    Medium
999      High
Name: writing_score, Length: 1000, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [87]:
data.head()

,parental level of education,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none,score_category,read_category,writing_score
0,bachelor's degree,0.193999,0.391492,0,1,0,0,0,1,1,Medium,Medium,Medium
1,some college,1.427476,1.313269,0,0,1,0,0,1,0,High,High,High
2,master's degree,1.770109,1.642475,0,1,0,0,0,1,1,High,High,High
3,associate's degree,-0.833899,-1.583744,1,0,0,0,0,0,1,Medium,Medium,Low
4,some college,0.605158,0.457333,1,0,1,0,0,1,1,Medium,Medium,Medium

In [89]:
#  Drop the original math_score column
data.drop(columns=['reading score','writing score'], inplace=True)

In [90]:
data.head()

,parental level of education,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none,score_category,read_category,writing_score
0,bachelor's degree,0,1,0,0,0,1,1,Medium,Medium,Medium
1,some college,0,0,1,0,0,1,0,High,High,High
2,master's degree,0,1,0,0,0,1,1,High,High,High
3,associate's degree,1,0,0,0,0,0,1,Medium,Medium,Low
4,some college,1,0,1,0,0,1,1,Medium,Medium,Medium

In [91]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data['score_category_encoded'] = label_encoder.fit_transform(data['score_category'])

In [93]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data['read_category_encoded'] = label_encoder.fit_transform(data['read_category'])

In [94]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
data['writing_category_encoded'] = label_encoder.fit_transform(data['writing_score'])

In [95]:
data.head()

,parental level of education,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none,score_category,read_category,writing_score,score_category_encoded,read_category_encoded,writing_category_encoded
0,bachelor's degree,0,1,0,0,0,1,1,Medium,Medium,Medium,2,2,2
1,some college,0,0,1,0,0,1,0,High,High,High,0,0,0
2,master's degree,0,1,0,0,0,1,1,High,High,High,0,0,0
3,associate's degree,1,0,0,0,0,0,1,Medium,Medium,Low,2,2,1
4,some college,1,0,1,0,0,1,1,Medium,Medium,Medium,2,2,2

In [96]:
data.drop(columns=['score_category','read_category','writing_score'], inplace=True)

In [97]:
data.head()

,parental level of education,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,lunch_standard,test preparation course_none,score_category_encoded,read_category_encoded,writing_category_encoded
0,bachelor's degree,0,1,0,0,0,1,1,2,2,2
1,some college,0,0,1,0,0,1,0,0,0,0
2,master's degree,0,1,0,0,0,1,1,0,0,0
3,associate's degree,1,0,0,0,0,0,1,2,2,1
4,some college,1,0,1,0,0,1,1,2,2,2

In [100]:
education_order = {
    'high school': 0,
    'some college': 1,
    'associate\'s degree': 2,
    'bachelor\'s degree': 3,
    'master\'s degree': 4
}

# Step 2: Apply the mapping to the column
data['parental level of education'] = data['parental level of education'].map(education_order)

In [ ]:
data